### PR TITLE
temp remove codecov and circleci config

### PR DESCRIPTION
**Pull request by WintersLu**
**Related issues**
Codecov Remediation (internal ticket: W-9559189)

**Describe the proposed solution**
Removing codecov due to security breach

**Describe alternatives you've considered**
Looking for code coverage replacement to codecov, alternatives will also need to be reviewed by CSIRT

### CODE REVIEW

**Review by nicodv — APPROVED** [review]
LGTM

**Comment by WintersLu** [comment]
@nicodv @crupley do you guys know if CircleCI config need to update? I dont have permission to view. Also granting me permission helps me experiment alternatives

**Comment by crupley** [comment]
Could you also remove from Travis build config?

https://github.com/salesforce/TransmogrifAI/blob/master/.travis.yml#L15-L16

**Comment by nicodv** [comment]
Please remove README badge for Codecov too, @WintersLu

**Comment by tovbinm** [comment]
Oh, was there another breach?

**Comment by WintersLu** [comment]
@tovbinm do you know why Travis is not triggered build? Is it caused by Travis config change?

**Comment by crupley** [comment]
@tovbinm no new breach, but because of the previous breach, Security team has mandated that we can no longer use codecov.

**Review by crupley — APPROVED** [review]

**Comment by tovbinm** [comment]
@WintersLu TravisCI has the following error:
Screen Shot 2021-07-23 at 10 49 44 AM

**Comment by tovbinm** [comment]
Please contact the Salesforce account administrator for TravisCI and bump up the plan.

**Pull request merged**
