### PR TITLE
Convert lambda functions into concrete classes to allow compatibility with Scala 2.11/2.12

### PR DESCRIPTION
**Pull request by tovbinm**
**Related issues**
Follows up on PR #274 and lands the foundation to support Scala 2.12 #332 

Scala 2.12 generates different class names for lambdas than Scala 2.1. Example:
```scala
object A {
  class Foo extends Function1[Int, Int] { def apply(v: Int): Int = v + 1 }
  def foo: Int => Int = x => x + 1
}
println(A.f.getClass.getName)
println(A.foo.getClass.getName)

Scala 2.11:
    A$Foo
    A$$anonfun$foo$1

Scala 2.12:
    A$Foo
    A$$$Lambda$13458/243505737
```
To maintain forward compatibility of models (so one won’t need to retrain models and would be able to load them in Scala 2.11/2.12) we would like to convert all the lambdas into concrete classes.

**Describe the proposed solution**
Changing all the lambdas with concrete classes.

**Describe alternatives you've considered**
NA

### CODE REVIEW

**Comment by wsuchy** [comment]
Imagine we move all lambdas to a companion object like this:
```class RichMapFeature {
....
(f.map[RealNN](RichMapFeatureLambdas.predictionToReal),
....
}

object RichMapFeatureLambdas{
val predictionToReal = (p: Prediction): RealNN => p.prediction.toRealNN
}
```
Still whenever try to inspect `RichMapFeatureLambdas.predictionToReal`  we get that random name under scala 2.12 and more deterministic value under scala 2.11, still not good.

But, given that we a priori know where are stored all lambdas for that class we could easily inspect our `RichMapFeatureLambdas` object and create a reverse lookup mapping all generated numbers to the property holding the actual function, e.g ` Lambda1$$$Lambda$4624/831965909@6259b7e5 -> RichMapFeatureLambdas.predictionToReal`

Then during the serialization we would simply use our map to replace compiler generated names  with class.property references. Because it would use run-time reflections the mapping would be always correct.

Finally the solution would work for both scala 2.11/2.12 and would be future proof with our macro.
@tovbinm

**Comment by tovbinm** [comment]
@wsuchy Sorry, I dont understand what exactly are you suggesting? what's wrong with the solution I propose in this PR?

**Comment by wsuchy** [comment]
@tovbinm Eventually we don't want our users to have to create manually their lambda functions as concrete classes and we know there is a solution (like the one I described). Although your changes apply only to the internal code  we will end up having two ways of dealing with lambdas. Also, modifying the code where you have to write functions manually isn't the greatest experience. This is the reason I proposed to use macro for generating these instead.

**Comment by tovbinm** [comment]
I think our macros would offer exactly the generation of concrete classes as proposed in this PR (since concrete classes are the most straightforward way to handle lambda functions in all scenarios possible, unless Scala decides to change their FunctionX interface of course, which is unlikely).

**Comment by wsuchy** [comment]
Unfortunately you don't have types present at macro evaluation time so you can't populate type params here: `Function1[???,???]`. Unless we don't want to write a compiler plugin of course.

**Comment by tovbinm** [comment]
Anonymous lambdas are much more difficult to debug and comprehend that simple classes, therefore I tend to assume that if simple macros spent work then we will have to write a compiler plugin if we decide to do so.

**Comment by tovbinm** [comment]
1. I followed all the changes that were done in #274 and changed chose to concrete classes.
2. No, these can be standalone classes that live outside objects.

**Pull request merged**
