### PR TITLE
test cases for RichListFeature

### PR DESCRIPTION
**Pull request by rajdeepd**
**Related issues**
None

**Describe the proposed solution**
This pull request helps improve code coverage and unit testing for RichListFeature

**Describe alternatives you've considered**
none

**Additional context**
This is first of series of commits i am planning to make

### CODE REVIEW

**Comment by rajdeepd** [comment]
> Thanks for the contribution! Unfortunately we can't verify the commit author(s): Rajdeep <r***@s***.com>. One possible solution is to [add that email to your GitHub account](https://github.com/settings/emails). Alternatively you can [change your commits to another email](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user) and force push the change. After getting your commits associated with your GitHub account, [refresh the status of this Pull Request](https://cla.salesforce.com/status/salesforce/TransmogrifAI/pull/207).

Added email id to the github account

**Comment by amateurhuman** [comment]
@rajdeepd you've been invited to the Salesforce org, once you accept the invitation you can refresh this PR by going to https://cla.salesforce.com/status/salesforce/TransmogrifAI/pull/207 to clear the CLA check

**Comment by tovbinm** [comment]
@rajdeepd Thanks for the contribution. I am no sure how this improves the coverage, as based on the metrics it seems to drop.
In any case, `tf()` is tested in `HashingTFTest` and `idf()` is tested in `IDFTest`. I can recommend you some other tasks if you'd like, hmm?

**Comment by rajdeepd** [comment]
Sure @tovbinm , but it was not clear how code coverage can go down

**Pull request closed without merging**
