### PR TITLE
Added missing test for java conversions

### PR DESCRIPTION
**Pull request by wsuchy**

### CODE REVIEW

**Comment by wsuchy** [comment]
My assumption was that this test should cover only the basic functionality (what it does by now). By looking at the coverage you can clearly see that all lines are now covered. I don't think that exploding the scope of it makes much sense as there are also different things to focus on.

**Comment by tovbinm** [comment]
well, the code that was introduced in #333 now clearly has a problem which I wanted you discover through the test:
```scala
import com.salesforce.op.features.types._
import collection.JavaConverters._
val jm = new java.util.HashMap[String, java.lang.Boolean]()
jm.put("nullValue", null)
jm.toBinaryMap // NullPointerException
```

**Comment by tovbinm** [comment]
I propose to add a test for null values and modify the code from #333 with following:
```scala
def toBinaryMap: BinaryMap = new BinaryMap(
    Option(v).map(_.asScala.collect { case (k, v) if v != null => v.booleanValue() } .toMap).getOrElse(Map.empty)
)
```

**Comment by wsuchy** [comment]
I am aware of that and assumed that you are fine with this by merging my PR.

**Comment by tovbinm** [comment]
Clearly we need to fix it as we don't want to have any NPE flying around.

**Comment by wsuchy** [comment]
Hmmm I wouldn't say that `null`s must be implicitly omitted. Why not convert them to false in Boolean and 0 in Integer?
Or maybe leave execptions as a suggestion for the user that there is a problem with the data.a

**Comment by tovbinm** [comment]
Replacing with default values would be even worse. Let's have then explicit handling for null values as follows, e.g. for RealMap:
```scala
def toRealMap: RealMap = new RealMap(
    Option(v).map(_.asScala.map {
      case (k, null) => (k, null.asInstanceOf[Double])
      case (k, x) => (k, x.doubleValue())
    }.toMap).getOrElse(Map.empty)
)
```

**Pull request merged**
