### PR TITLE
Changes to allow passing reader as optional param to be able to  gene…

### PR DESCRIPTION
**Pull request by yufeldman**
…rateDataFrame based on the outside reader

versus reader set on the workflowmodel, as latter one can be cached

**Related issues**
Refer to issue(s) addressed in this pull request from [Issues](https://github.com/salesforce/TransmogrifAI/issues) page.

**Describe the proposed solution**
A clear and concise description of what the changes are.

**Describe alternatives you've considered**

**Additional context**
Add any other context about the changes here.

### CODE REVIEW

**Comment by leahmcguire** [comment]
You can always change the reader on a workflow  or workflow model using `setReader`.  It just seems confusing to add another way to do this

**Comment by yufeldman** [comment]
> You can always change the reader on a workflow or workflow model using `setReader`. It just seems confusing to add another way to do this

workflow is cached, if I set a reader on it, it won't work with concurrent requests. This is my amateur way of fixing caching issues - I will be discussing it, so it may change completely. This PR was more of a reference point - at least at first

**Comment by amateurhuman** [comment]
@yufeldman you've been invited to the org, once you accept it you can refresh the CLA check by going to https://cla.salesforce.com/status/salesforce/TransmogrifAI/pull/268

**Comment by leahmcguire** [comment]
Are you working on streaming? we have a separate flow for streaming https://github.com/salesforce/TransmogrifAI/blob/master/core/src/main/scala/com/salesforce/op/OpWorkflowRunner.scala#L232

**Comment by tovbinm** [comment]
@leahmcguire we just discussed with @yufeldman how to allow what they need. I opened a PR to do that #270

**Pull request closed without merging**
