### PR TITLE
Add/upgrade string indexing tests

### PR DESCRIPTION
**Pull request by crupley**
**Related issues**
Improve test coverage for transformers & estimators https://github.com/salesforce/TransmogrifAI/issues/278

**Describe the proposed solution**

* Separate tests for `OpStringIndexer` and `OpStringIndexerNoFilter`
* Upgrade tests to use Op Transformer/Estimator Spec
    * `OpStringIndexerNoFilterTest`
    * `OpIndexToStringNoFilterTest`

**Describe alternatives you've considered**

Attempted to upgrade `OpStringIndexerTest` and `OpIndexToStringTest` but these both extend an wrapper-type class that is not compatible with the new test spec.

**Additional context**
None

### CODE REVIEW

**Comment by tovbinm** [comment]
@crupley can you elaborate what's not working with the base specs and wrapper staged? (cc @snabar)

**Comment by crupley** [comment]
Signature of the transformer spec is:

```
abstract class OpTransformerSpec[O <: FeatureType : WeakTypeTag : ClassTag,
TransformerType <: OpPipelineStage[O] with Transformer with OpTransformer : ClassTag]
```

The transformer passed must inherit from OpPipelineStage, Transformer, and OpTransformer. OpTransformerWrapper is missing the OpTransformer piece.

**Comment by tovbinm** [comment]
Ha! True. Its actually on purpose :) ok! So we need a new base class for testing wrapped stages then.

**Comment by tovbinm** [comment]
@crupley here you go - https://github.com/salesforce/TransmogrifAI/pull/295

**Pull request merged**
