### PR TITLE
0.6.2 release

### PR DESCRIPTION
**Pull request by sanmitra**
##

Bug fixes
- Fix `ModelInsightsTest` flakiness due to coefficients turning negative [#407](https://github.com/salesforce/TransmogrifAI/pull/407)

##

New features/updates
- Turn off logging of tokens [#420](https://github.com/salesforce/TransmogrifAI/pull/420)
- Regression training limit [#413](https://github.com/salesforce/TransmogrifAI/pull/413)

### CODE REVIEW

**Comment by tovbinm** [comment]
@sanmitra please update the version in all the other place (see #403)

**Comment by leahmcguire** [comment]
We need to remove the logging since I reverted Tuans change

**Comment by sanmitra** [comment]
@tovbinm @leahmcguire please review again. Thanks

**Comment by tovbinm** [comment]
@sanmitra  Have you published the artifacts already? I do not see them neither on bintray nor on central.

**Comment by tovbinm** [comment]
@sanmitra  Ping ;)

**Comment by sanmitra** [comment]
@tovbinm we can close this PR. I made this PR just to release `Turn off logging of tokens #420` for E1 AutoML as it could have caused security issue. But instead of public release, we just made an internal release for E1 AutoML thanks to Gera for setting that up. Anyways, we are planning on a separate public release soon.

**Pull request closed without merging**
