### PR TITLE
Possible solution for issue #154 (Geolocation to Country transformer)

### PR DESCRIPTION
**Pull request by ybh6336**
Uses reverse geolocation lookup code at https://github.com/AReallyGoodName/OfflineReverseGeocode

**Related issues**
https://github.com/salesforce/TransmogrifAI/issues/154

**Describe the proposed solution**
The proposed solution, implemented in com.salesforce.op.stages.impl.feature.GeolocationToCountryTransformer, uses latitude and longitude of Geolocation to look up the country code. It uses an offline reverse geocode lookup code at https://github.com/AReallyGoodName/OfflineReverseGeocode. The database for offline lookup is in file core/src/main/resources/geolocation/cities1000.txt. This file has been downloaded from http://download.geonames.org/export/dump/.
The companion object, GeolocationToCountryTransformer, loads the file once, which is then referenced as a static field.

**Describe alternatives you've considered**
An alternative approach is to perform a reverse lookup using a remote service, like the ones listed below:
http://www.geonames.org/export/web-services.html#countrysubdiv
https://developers.google.com/maps/documentation/geocoding/start?csw=1#ReverseGeocoding
Drawbacks:
- needs API license
- latency
- would need a fallback offline approach

**Additional context**
None

### CODE REVIEW

**Comment by ybh6336** [comment]
Unfortunately, https://github.com/AReallyGoodName/OfflineReverseGeocode has not been published to maven central, so had to copy code here (with copyright header and link to the original repository).

**Comment by tovbinm** [comment]
@ybh6336 thank you for your contribution.

The dataset `cities1000.txt` is under `Creative Commons Attribution 4.0 License` (https://creativecommons.org/licenses/by/4.0). I need to verify with our legal department if it's ok to include or not.

**Comment by ybh6336** [comment]
Thanks @tovbinm. I will look into `lucene-spatial3d`.

**Comment by tovbinm** [comment]
Also have a look on this one - https://s2geometry.io/. They might have a java interface that we could use.

**Comment by tovbinm** [comment]
@ybh6336 try this one using lucene. It's as simple as this: 1. index all cities 2. query then with radius around lat/lon - https://medium.com/@janakachathuranga/indexing-geographical-data-with-lucene-6-4ade78eac1ab

**Comment by tovbinm** [comment]
@ybh6336 How are you doing?

I just got back an answer from our legal department. Unfortunately we wont be able to include this dataset in our repository. Unless we find another dataset with BSD-3 or Apache 2.0 license, create our own instead. 

Alternatively we can add instructions for users on how they can download and include the dataset themselves. Based on my previous experience, it would be cumbersome, error prone and would create bad user experience. So this is the least preferred option.

**Comment by vpatryshev** [comment]
Is it legal then to include a link to this file, and load it on demand. In
this case it's not us, it's the user that loads the file, no?

Thanks,
-Vlad

**Comment by tovbinm** [comment]
#227

**Pull request closed without merging**
