### PR TITLE
Use available CPU cores for Junit and Spark local

### PR DESCRIPTION
**Pull request by gerashegalov**
Current build underutilizes available cores. Speed up local test by increasing degree of parallelism and  available cores in junit and spark.

### CODE REVIEW

**Comment by gerashegalov** [comment]
This tests fail when we have the higher DOP:
```
OpRandomForestClassifierTest. OpRandomForestClassifier model should transform data
OpRandomForestClassifierTest. OpRandomForestClassifier model should transform data after being loaded
OpRandomForestClassifierTest. OpRandomForestClassifier model should transform key/value
OpRandomForestClassifierTest. OpRandomForestClassifier model should transform maps
OpRandomForestClassifierTest. OpRandomForestClassifier model should transform rows
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] model should transform data
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] model should transform data after being loaded
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] model should transform key/value
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] model should transform maps
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] model should transform rows
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] should not clean the variable names when clean text is set to false
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] should return only the elements that exceed the minimum support requirement when minSupport is set
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] should return only the specified number of elements when top K is set
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] should return the a fitted vectorizer with the correct default parameters
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] should return the expected vector with the default param settings
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] should track nulls when clean text is set to false
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] should track nulls when minSupport is set
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] should track nulls when top K is set
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] should track nulls with the correct default parameters
MultiPickListMapVectorizerTest. MultiPickListMapVectorizer[OPVector] should track nulls with the default param settings
OPMapVectorizerTest. TextMapPivotVectorizer should return the expected vector with the default param settings
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] model should transform data
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] model should transform data after being loaded
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] model should transform key/value
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] model should transform maps
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] model should transform rows
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] should not clean the variable names when clean text is set to false
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] should return only the elements that exceed the minimum support requirement when minSupport is set
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] should return only the specified number of elements when top K is set
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] should return the a fitted vectorizer with the correct parameters
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] should return the expected vector with the default param settings
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] should track nulls
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] should track nulls the elements that exceed the minimum support requirement when minSupport is set
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] should track nulls the specified number of elements when top K is set
TextMapPivotVectorizerTest. TextMapPivotVectorizer[OPVector] should track nulls when clean text is set to false
OpGeneralizedLinearRegressionTest. OpGeneralizedLinearRegression model should transform data
OpGeneralizedLinearRegressionTest. OpGeneralizedLinearRegression model should transform data after being loaded
OpGeneralizedLinearRegressionTest. OpGeneralizedLinearRegression model should transform key/value
OpGeneralizedLinearRegressionTest. OpGeneralizedLinearRegression model should transform maps
OpGeneralizedLinearRegressionTest. OpGeneralizedLinearRegression model should transform rows
OpRandomForestRegressorTest. OpRandomForestRegressor model should transform data
OpRandomForestRegressorTest. OpRandomForestRegressor model should transform data after being loaded
OpRandomForestRegressorTest. OpRandomForestRegressor model should transform key/value
OpRandomForestRegressorTest. OpRandomForestRegressor model should transform maps
OpRandomForestRegressorTest. OpRandomForestRegressor model should transform rows
```

**Comment by tovbinm** [comment]
Seems to pass on TravisCI and CircleCI. Does it only fail on your machine?

Some of the tests might produce slight different results due to how Spark shuffles the data with the increased parallelism.

**Comment by tovbinm** [comment]
BTW, another speed up can come from not shutting down Spark Session between the tests and not deleting the temp folder as we do it in our SparkTestBase. My 5c: I did try it in the past and it was NOT significantly faster.

**Comment by gerashegalov** [comment]
Adding DO NOT MERGE for now because it will generate false test failures. We need to first make test results independent of DOP.

@leahmcguire @Jauntbox if you'd like to take a look at / confirm the test failures locally you can checkout the branch by following these [instructions](https://blog.scottlowe.org/2015/09/04/checking-out-github-pull-requests-locally)

**Comment by tovbinm** [comment]
any updates on this one?

**Comment by gerashegalov** [comment]
no updates, have not had the time to make tests independent of parallelism

**Pull request closed without merging**
